### ISSUE TITLE
iPhoneOS SDK 14.3 / Xcode 12.3 build issue tracking

### ISSUE THREAD

**Issue by micolous** [metrodroid/metrodroid#747]
At present, Metrodroid doesn't build properly on iPhoneOS 14.3 SDK and Xcode 12.3, probably because the version of Kotlin is too old to support it.  I've started rolling forward in #746, but this requires a huge number of changes to the code, because of underlying API changes, so it's not going to be fixed in 3.1.0.

Rolling forward to:

```gradle
        kotlin_version = '1.3.50'
        kotlinio_version = '0.1.13-1.3.50-eap-5'
        kotlinserial_version = '0.12.0'
```

Seems to fix a bunch of the Kotlin/Native compatibility issues, but then doesn't build with `SDK_NAME=iphoneos14.3  ./gradlew :cinteropStationsIOS`.

The closest I've gotten to actually building results in:

```
Exception in thread "main" java.lang.Error: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.3.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSURL.h:10:9: fatal error: 'Foundation/NSURLHandle.h' file not found
```

This also fails inside of the Xcode environment.  It looks like it's tripping up in this part of `NSURL.h`:

```objc
#if TARGET_OS_OSX || TARGET_OS_MACCATALYST
#import <Foundation/NSURLHandle.h>
#endif
```

For some reason, the SDK target detection is all wrong, and attempts to "bypass it" have not been fruitful.  https://github.com/NativeScript/NativeScript/issues/8741#issuecomment-715407698 looks like a promising lead.

Without `SDK_NAME` set, it builds fine, presumably because `NSURLHandle.h` exists in the macOS SDK.  Building for the iOS Simulator is also fine.
